version: '3.9'

services:
  ms-eureka:
    container_name: ms-eureka
    restart: always
    image: sonatype-nexus.backhole.ovh/ms-eureka-service:${IMAGE_VERSION:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"