version: '3.9'

services:
  eureka:
    container_name: eureka
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - spring.config.import=optional:configserver:http://config-service:8089

    #command: ["java", "-jar", "/app.jar"]

    networks:
      - spring-network

networks:
  spring-network:
    name: spring-network
    driver: bridge

# docker-compose up -d