version: '3.9'

services:
  eureka:
    container_name: eureka
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile-DEV
      args:
        - CONFIG_SERVICE_URI_ARG=${IP_DEV}
        - env_profile=${env_Dev}
    image: ms-eureka-service
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=${env_Dev}
      - CONFIG_SERVICE_URI=${IP_DEV}

    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

# docker-compose up -d