version: '3.9'

services:
  eureka:
    container_name: eureka
    restart: always
    image: ms-eureka-service:${version:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args: # pour la construction de l'image
        - SPRING_PROFILES_ACTIVE=${profile_actif_dev}
        - CONFIG_SERVICE_URI=${service_config_host_dev}
    ports:
      - "8099:8099"
    environment: # pour la construction du conteneur
      - SPRING_PROFILES_ACTIVE=${profile_actif_dev}
      - CONFIG_SERVICE_URI=${service_config_docker}
    networks:
      - keycloak_postgre

networks:
  keycloak_postgre:
    name: sso_bd
    driver: bridge    # indic le type de réseau docker