version: '3.9'

services:
  eureka:
    container_name: eureka
    restart: always
    image: ms-eureka-service:${version:-latest}
    build:
      context: ../
      dockerfile: dockerfile
      args:
        - CONFIG_SERVICE_URI_ARG=${IP_DEV}
        - env_profile=${env_DEV}
    env_file:
      - .env
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=${env_DEV}
      - CONFIG_SERVICE_URI=${IP_DEV}

    networks:
      - keycloak_postgre

networks:
  keycloak_postgre:
    name: sso_bd
    external: true    # indic qui ce connectera au réseau existant blog-network
    driver: bridge    # indic le type de réseau docker